#pragma once

// kamimodo™ - the legacy of GODMODE_999 © 2025 ____l____e____x____e____r____

#include <godmode.foundation/$_preprocessor.h>

#define godmode_engine(...) namespace$_2(godmode, engine, __VA_ARGS__)
#define godmode_engine_core(...) namespace$_3(godmode, engine, core, __VA_ARGS__)
#define godmode_engine_editor(...) namespace$_3(godmode, engine, editor, __VA_ARGS__)
#define godmode_engine_entity(...) namespace$_3(godmode, engine, entity, __VA_ARGS__)
#define godmode_engine_entity__2d(...) namespace$_4(godmode, engine, entity, _2d, __VA_ARGS__)
#define godmode_engine_entity__3d(...) namespace$_4(godmode, engine, entity, _3d, __VA_ARGS__)
#define godmode_engine_events(...) namespace$_3(godmode, engine, events, __VA_ARGS__)
#define godmode_engine_graphics(...) namespace$_3(godmode, engine, graphics, __VA_ARGS__)
#define godmode_engine_graphics_effects(...) namespace$_4(godmode, engine, graphics, effects, __VA_ARGS__)
#define godmode_engine_input(...) namespace$_3(godmode, engine, input, __VA_ARGS__)
#define godmode_engine_logic(...) namespace$_3(godmode, engine, logic, __VA_ARGS__)
#define godmode_engine_logic__2d(...) namespace$_4(godmode, engine, logic, _2d, __VA_ARGS__)
#define godmode_engine_logic__3d(...) namespace$_4(godmode, engine, logic, _3d, __VA_ARGS__)
#define godmode_engine_math(...) namespace$_3(godmode, engine, math, __VA_ARGS__)
#define godmode_engine_network(...) namespace$_3(godmode, engine, network, __VA_ARGS__)
#define godmode_engine_physics(...) namespace$_3(godmode, engine, physics, __VA_ARGS__)
#define godmode_engine_sound(...) namespace$_3(godmode, engine, sound, __VA_ARGS__)
#define godmode_engine_system(...) namespace$_3(godmode, engine, system, __VA_ARGS__)
#define godmode_engine_ui(...) namespace$_3(godmode, engine, ui, __VA_ARGS__)
#define godmode_engine_ui_apps(...) namespace$_4(godmode, engine, ui, apps, __VA_ARGS__)
#define godmode_engine_ui_components(...) namespace$_4(godmode, engine, ui, components, __VA_ARGS__)
#define godmode_engine_ui_dialogs(...) namespace$_4(godmode, engine, ui, dialogs, __VA_ARGS__)
#define godmode_engine_utils(...) namespace$_3(godmode, engine, utils, __VA_ARGS__)

#define godmode_engine_$ namespace$_2_$(godmode, engine)
#define godmode_engine_core_$ namespace$_3_$(godmode, engine, core)
#define godmode_engine_editor_$ namespace$_3_$(godmode, engine, editor)
#define godmode_engine_entity_$ namespace$_3_$(godmode, engine, entity)
#define godmode_engine_entity__2d_$ namespace$_4_$(godmode, engine, entity, _2d)
#define godmode_engine_entity__3d_$ namespace$_4_$(godmode, engine, entity, _3d)
#define godmode_engine_events_$ namespace$_3_$(godmode, engine, events)
#define godmode_engine_graphics_$ namespace$_3_$(godmode, engine, graphics)
#define godmode_engine_graphics_effects_$ namespace$_4_$(godmode, engine, graphics, effects)
#define godmode_engine_input_$ namespace$_3_$(godmode, engine, input)
#define godmode_engine_logic_$ namespace$_3_$(godmode, engine, logic)
#define godmode_engine_logic__2d_$ namespace$_4_$(godmode, engine, logic, _2d)
#define godmode_engine_logic__3d_$ namespace$_4_$(godmode, engine, logic, _3d)
#define godmode_engine_math_$ namespace$_3_$(godmode, engine, math)
#define godmode_engine_network_$ namespace$_3_$(godmode, engine, network)
#define godmode_engine_physics_$ namespace$_3_$(godmode, engine, physics)
#define godmode_engine_sound_$ namespace$_3_$(godmode, engine, sound)
#define godmode_engine_system_$ namespace$_3_$(godmode, engine, system)
#define godmode_engine_ui_$ namespace$_3_$(godmode, engine, ui)
#define godmode_engine_ui_apps_$ namespace$_4_$(godmode, engine, ui, apps)
#define godmode_engine_ui_components_$ namespace$_4_$(godmode, engine, ui, components)
#define godmode_engine_ui_dialogs_$ namespace$_4_$(godmode, engine, ui, dialogs)
#define godmode_engine_utils_$ namespace$_3_$(godmode, engine, utils)

#define godmode_engine_$$ namespace$_2_$$(godmode, engine)
#define godmode_engine_core_$$ namespace$_3_$$(godmode, engine, core)
#define godmode_engine_editor_$$ namespace$_3_$$(godmode, engine, editor)
#define godmode_engine_entity_$$ namespace$_3_$$(godmode, engine, entity)
#define godmode_engine_entity__2d_$$ namespace$_4_$$(godmode, engine, entity, _2d)
#define godmode_engine_entity__3d_$$ namespace$_4_$$(godmode, engine, entity, _3d)
#define godmode_engine_events_$$ namespace$_3_$$(godmode, engine, events)
#define godmode_engine_graphics_$$ namespace$_3_$$(godmode, engine, graphics)
#define godmode_engine_graphics_effects_$$ namespace$_4_$$(godmode, engine, graphics, effects)
#define godmode_engine_input_$$ namespace$_3_$$(godmode, engine, input)
#define godmode_engine_logic_$$ namespace$_3_$$(godmode, engine, logic)
#define godmode_engine_logic__2d_$$ namespace$_4_$$(godmode, engine, logic, _2d)
#define godmode_engine_logic__3d_$$ namespace$_4_$$(godmode, engine, logic, _3d)
#define godmode_engine_math_$$ namespace$_3_$$(godmode, engine, math)
#define godmode_engine_network_$$ namespace$_3_$$(godmode, engine, network)
#define godmode_engine_physics_$$ namespace$_3_$$(godmode, engine, physics)
#define godmode_engine_sound_$$ namespace$_3_$$(godmode, engine, sound)
#define godmode_engine_system_$$ namespace$_3_$$(godmode, engine, system)
#define godmode_engine_ui_$$ namespace$_3_$$(godmode, engine, ui)
#define godmode_engine_ui_apps_$$ namespace$_4_$$(godmode, engine, ui, apps)
#define godmode_engine_ui_components_$$ namespace$_4_$$(godmode, engine, ui, components)
#define godmode_engine_ui_dialogs_$$ namespace$_4_$$(godmode, engine, ui, dialogs)
#define godmode_engine_utils_$$ namespace$_3_$$(godmode, engine, utils)

#define godmode_engine$extern(name, ...) global$_2(godmode, engine, name, __VA_ARGS__)
#define godmode_engine_core$extern(name, ...) global$_3(godmode, engine, core, name, __VA_ARGS__)
#define godmode_engine_editor$extern(name, ...) global$_3(godmode, engine, editor, name, __VA_ARGS__)
#define godmode_engine_entity$extern(name, ...) global$_3(godmode, engine, entity, name, __VA_ARGS__)
#define godmode_engine_entity__2d$extern(name, ...) global$_4(godmode, engine, entity, _2d, name, __VA_ARGS__)
#define godmode_engine_entity__3d$extern(name, ...) global$_4(godmode, engine, entity, _3d, name, __VA_ARGS__)
#define godmode_engine_events$extern(name, ...) global$_3(godmode, engine, events, name, __VA_ARGS__)
#define godmode_engine_graphics$extern(name, ...) global$_3(godmode, engine, graphics, name, __VA_ARGS__)
#define godmode_engine_graphics_effects$extern(name, ...) global$_4(godmode, engine, graphics, effects, name, __VA_ARGS__)
#define godmode_engine_input$extern(name, ...) global$_3(godmode, engine, input, name, __VA_ARGS__)
#define godmode_engine_logic$extern(name, ...) global$_3(godmode, engine, logic, name, __VA_ARGS__)
#define godmode_engine_logic__2d$extern(name, ...) global$_4(godmode, engine, logic, _2d, name, __VA_ARGS__)
#define godmode_engine_logic__3d$extern(name, ...) global$_4(godmode, engine, logic, _3d, name, __VA_ARGS__)
#define godmode_engine_math$extern(name, ...) global$_3(godmode, engine, math, name, __VA_ARGS__)
#define godmode_engine_network$extern(name, ...) global$_3(godmode, engine, network, name, __VA_ARGS__)
#define godmode_engine_physics$extern(name, ...) global$_3(godmode, engine, physics, name, __VA_ARGS__)
#define godmode_engine_sound$extern(name, ...) global$_3(godmode, engine, sound, name, __VA_ARGS__)
#define godmode_engine_system$extern(name, ...) global$_3(godmode, engine, system, name, __VA_ARGS__)
#define godmode_engine_ui$extern(name, ...) global$_3(godmode, engine, ui, name, __VA_ARGS__)
#define godmode_engine_ui_apps$extern(name, ...) global$_4(godmode, engine, ui, apps, name, __VA_ARGS__)
#define godmode_engine_ui_components$extern(name, ...) global$_4(godmode, engine, ui, components, name, __VA_ARGS__)
#define godmode_engine_ui_dialogs$extern(name, ...) global$_4(godmode, engine, ui, dialogs, name, __VA_ARGS__)
#define godmode_engine_utils$extern(name, ...) global$_3(godmode, engine, utils, name, __VA_ARGS__)