#pragma once

// kamimodo™ - the legacy of GODMODE_999 © 2025 ____l____e____x____e____r____

#include <godmode.foundation/$_preprocessor.h>

#define godmode$(...) namespace$_1(godmode, __VA_ARGS__)
#define godmode_foundation(...) namespace$_2(godmode, foundation, __VA_ARGS__)
#define godmode_foundation_ai(...) namespace$_3(godmode, foundation, ai, __VA_ARGS__)
#define godmode_foundation_async(...) namespace$_3(godmode, foundation, async, __VA_ARGS__)
#define godmode_foundation_core(...) namespace$_3(godmode, foundation, core, __VA_ARGS__)
#define godmode_foundation_crypto(...) namespace$_3(godmode, foundation, crypto, __VA_ARGS__)
#define godmode_foundation_events(...) namespace$_3(godmode, foundation, events, __VA_ARGS__)
#define godmode_foundation_file(...) namespace$_3(godmode, foundation, file, __VA_ARGS__)
#define godmode_foundation_log(...) namespace$_3(godmode, foundation, log, __VA_ARGS__)
#define godmode_foundation_network(...) namespace$_3(godmode, foundation, network, __VA_ARGS__)
#define godmode_foundation_serialization(...) namespace$_3(godmode, foundation, serialization, __VA_ARGS__)
#define godmode_foundation_system(...) namespace$_3(godmode, foundation, system, __VA_ARGS__)
#define godmode_foundation_test(...) namespace$_3(godmode, foundation, test, __VA_ARGS__)
#define godmode_foundation_time(...) namespace$_3(godmode, foundation, time, __VA_ARGS__)
#define godmode_foundation_types(...) namespace$_3(godmode, foundation, types, __VA_ARGS__)

#define godmode_$ namespace$_1_$(godmode)
#define godmode_foundation_$ namespace$_2_$(godmode, foundation)
#define godmode_foundation_ai_$ namespace$_3_$(godmode, foundation, ai)
#define godmode_foundation_async_$ namespace$_3_$(godmode, foundation, async)
#define godmode_foundation_core_$ namespace$_3_$(godmode, foundation, core)
#define godmode_foundation_crypto_$ namespace$_3_$(godmode, foundation, crypto)
#define godmode_foundation_events_$ namespace$_3_$(godmode, foundation, events)
#define godmode_foundation_file_$ namespace$_3_$(godmode, foundation, file)
#define godmode_foundation_log_$ namespace$_3_$(godmode, foundation, log)
#define godmode_foundation_network_$ namespace$_3_$(godmode, foundation, network)
#define godmode_foundation_serialization_$ namespace$_3_$(godmode, foundation, serialization)
#define godmode_foundation_system_$ namespace$_3_$(godmode, foundation, system)
#define godmode_foundation_test_$ namespace$_3_$(godmode, foundation, test)
#define godmode_foundation_time_$ namespace$_3_$(godmode, foundation, time)
#define godmode_foundation_types_$ namespace$_3_$(godmode, foundation, types)

#define godmode_$$ namespace$_1_$$(godmode)
#define godmode_foundation_$$ namespace$_2_$$(godmode, foundation)
#define godmode_foundation_ai_$$ namespace$_3_$$(godmode, foundation, ai)
#define godmode_foundation_async_$$ namespace$_3_$$(godmode, foundation, async)
#define godmode_foundation_core_$$ namespace$_3_$$(godmode, foundation, core)
#define godmode_foundation_crypto_$$ namespace$_3_$$(godmode, foundation, crypto)
#define godmode_foundation_events_$$ namespace$_3_$$(godmode, foundation, events)
#define godmode_foundation_file_$$ namespace$_3_$$(godmode, foundation, file)
#define godmode_foundation_log_$$ namespace$_3_$$(godmode, foundation, log)
#define godmode_foundation_network_$$ namespace$_3_$$(godmode, foundation, network)
#define godmode_foundation_serialization_$$ namespace$_3_$$(godmode, foundation, serialization)
#define godmode_foundation_system_$$ namespace$_3_$$(godmode, foundation, system)
#define godmode_foundation_test_$$ namespace$_3_$$(godmode, foundation, test)
#define godmode_foundation_time_$$ namespace$_3_$$(godmode, foundation, time)
#define godmode_foundation_types_$$ namespace$_3_$$(godmode, foundation, types)

#define godmode$extern(...) global$_1(godmode, __VA_ARGS__)
#define godmode_foundation$extern(...) global$_2(godmode, foundation, __VA_ARGS__)
#define godmode_foundation_ai$extern(name, ...) global$_3(godmode, foundation, ai, name, __VA_ARGS__)
#define godmode_foundation_async$extern(name, ...) global$_3(godmode, foundation, async, name, __VA_ARGS__)
#define godmode_foundation_core$extern(name, ...) global$_3(godmode, foundation, core, name, __VA_ARGS__)
#define godmode_foundation_crypto$extern(name, ...) global$_3(godmode, foundation, crypto, name, __VA_ARGS__)
#define godmode_foundation_events$extern(name, ...) global$_3(godmode, foundation, events, name, __VA_ARGS__)
#define godmode_foundation_file$extern(name, ...) global$_3(godmode, foundation, file, name, __VA_ARGS__)
#define godmode_foundation_log$extern(name, ...) global$_3(godmode, foundation, log, name, __VA_ARGS__)
#define godmode_foundation_network$extern(name, ...) global$_3(godmode, foundation, network, name, __VA_ARGS__)
#define godmode_foundation_serialization$extern(name, ...) global$_3(godmode, foundation, serialization, name, __VA_ARGS__)
#define godmode_foundation_system$extern(name, ...) global$_3(godmode, foundation, system, name, __VA_ARGS__)
#define godmode_foundation_test$extern(name, ...) global$_3(godmode, foundation, test, name, __VA_ARGS__)
#define godmode_foundation_time$extern(name, ...) global$_3(godmode, foundation, time, name, __VA_ARGS__)
#define godmode_foundation_types$extern(name, ...) global$_3(godmode, foundation, types, name, __VA_ARGS__)