#pragma once
#include <godmode.engine/$_namespaces.h>

//  kamimodo™ - the legacy of GODMODE_999
//  Copyright © 2025 ____l____e____x____e____r____. All rights reserved.
//
//  This file is part of the kamimodo™ codebase.
//
//  Licensed under the Light Attribution License (LAL) 1.0.
//  See the LICENSE file in the project root or visit:
//  https://7EX.LEX3R.com/$/999/kamimodo™/LICENSE
//
//  Trademarks:
//  kamimodo™ and kamimodo SDK™ are trademarks of ____l____e____x____e____r____.
//
//  Legacy reference:
//  GODMODE_999 — the underground predecessor that evolved into KAMIMODO.

#include <godmode.engine/GodmodeEngine.h>
#include <godmode.engine/core/ApiFactory.h>
#include <godmode.engine/core/Content.h>
#include <godmode.engine/core/ContentType.h>
#include <godmode.engine/core/EngineRuntime.h>
#include <godmode.engine/editor/Editor.h>
#include <godmode.engine/editor/EditorEngine.h>
#include <godmode.engine/editor/EditorInterface.h>
#include <godmode.engine/editor/EditorSettings.h>
#include <godmode.engine/editor/Project.h>
#include <godmode.engine/editor/Selector.h>
#include <godmode.engine/editor/TransformAxisType.h>
#include <godmode.engine/editor/TransformController.h>
#include <godmode.engine/editor/TransformToolbar.h>
#include <godmode.engine/editor/TransformType.h>
#include <godmode.engine/entity/BaseEntity.h>
#include <godmode.engine/entity/BaseEntity2d.h>
#include <godmode.engine/entity/BaseEntity3d.h>
#include <godmode.engine/entity/EntityFactory.h>
#include <godmode.engine/entity/_2d/Line2d.h>
#include <godmode.engine/entity/_2d/Line2dFixed.h>
#include <godmode.engine/entity/_2d/LineRectangle.h>
#include <godmode.engine/entity/_2d/Particles2d.h>
#include <godmode.engine/entity/_2d/Point2d.h>
#include <godmode.engine/entity/_2d/Sprite.h>
#include <godmode.engine/entity/_2d/SpriteFixed.h>
#include <godmode.engine/entity/_2d/SpriteFullScreen.h>
#include <godmode.engine/entity/_2d/SpriteVertexPrecision.h>
#include <godmode.engine/entity/_2d/Text2d.h>
#include <godmode.engine/entity/_3d/Line3d.h>
#include <godmode.engine/entity/_3d/LineBox.h>
#include <godmode.engine/entity/_3d/Object3d.h>
#include <godmode.engine/entity/_3d/Particles.h>
#include <godmode.engine/entity/_3d/Point.h>
#include <godmode.engine/entity/_3d/SkyBox.h>
#include <godmode.engine/events/BaseEntity3dSelectEvent.h>
#include <godmode.engine/events/ClickEvent.h>
#include <godmode.engine/events/ContentChangeEvent.h>
#include <godmode.engine/events/FileOpenEvent.h>
#include <godmode.engine/events/FileSavedEvent.h>
#include <godmode.engine/events/Scene3dChangeEvent.h>
#include <godmode.engine/events/SceneStateChangeEvent.h>
#include <godmode.engine/events/WindowCloseEvent.h>
#include <godmode.engine/graphics/Color.h>
#include <godmode.engine/graphics/ColorChannel.h>
#include <godmode.engine/graphics/CubeTexture.h>
#include <godmode.engine/graphics/CubeTextureFace.h>
#include <godmode.engine/graphics/Display.h>
#include <godmode.engine/graphics/DisplayMode.h>
#include <godmode.engine/graphics/Effect.h>
#include <godmode.engine/graphics/EffectFactory.h>
#include <godmode.engine/graphics/effects/ASCII.h>
#include <godmode.engine/graphics/effects/Bloom.h>
#include <godmode.engine/graphics/effects/Blur.h>
#include <godmode.engine/graphics/effects/ColorAdjust.h>
#include <godmode.engine/graphics/effects/Colorblindness.h>
#include <godmode.engine/graphics/effects/ColorblindnessType.h>
#include <godmode.engine/graphics/effects/DepthOfField.h>
#include <godmode.engine/graphics/effects/EdgeDetect.h>
#include <godmode.engine/graphics/effects/Fog.h>
#include <godmode.engine/graphics/effects/Grain.h>
#include <godmode.engine/graphics/effects/Grayscale.h>
#include <godmode.engine/graphics/effects/HaloLensFlare.h>
#include <godmode.engine/graphics/effects/HighDynamicRange.h>
#include <godmode.engine/graphics/effects/LightShafts.h>
#include <godmode.engine/graphics/effects/MotionBlur.h>
#include <godmode.engine/graphics/effects/Sepia.h>
#include <godmode.engine/graphics/effects/Sharpen.h>
#include <godmode.engine/graphics/effects/SSAO.h>
#include <godmode.engine/graphics/effects/SSR.h>
#include <godmode.engine/graphics/Effects.h>
#include <godmode.engine/graphics/Font.h>
#include <godmode.engine/graphics/FontDrawingOptions.h>
#include <godmode.engine/graphics/GraphicsApi.h>
#include <godmode.engine/graphics/GraphicsDevice.h>
#include <godmode.engine/graphics/GraphicsEntity.h>
#include <godmode.engine/graphics/GraphicsFactory.h>
#include <godmode.engine/graphics/IndexFormat.h>
#include <godmode.engine/graphics/IndexFormatType.h>
#include <godmode.engine/graphics/Material.h>
#include <godmode.engine/graphics/Model.h>
#include <godmode.engine/graphics/ModelPreview.h>
#include <godmode.engine/graphics/ModelVertex.h>
#include <godmode.engine/graphics/PostProcessor.h>
#include <godmode.engine/graphics/PreProcessor.h>
#include <godmode.engine/graphics/Renderer.h>
#include <godmode.engine/graphics/Shader.h>
#include <godmode.engine/graphics/ShaderManager.h>
#include <godmode.engine/graphics/ShaderParameters.h>
#include <godmode.engine/graphics/Surface.h>
#include <godmode.engine/graphics/Texture.h>
#include <godmode.engine/graphics/VertexFormat.h>
#include <godmode.engine/input/Gamepad.h>
#include <godmode.engine/input/InputApi.h>
#include <godmode.engine/input/InputDevice.h>
#include <godmode.engine/input/InputFactory.h>
#include <godmode.engine/input/Key.h>
#include <godmode.engine/input/Keyboard.h>
#include <godmode.engine/input/KeyState.h>
#include <godmode.engine/input/Kinect.h>
#include <godmode.engine/input/Mouse.h>
#include <godmode.engine/input/MouseButton.h>
#include <godmode.engine/logic/BoundingBox.h>
#include <godmode.engine/logic/Camera.h>
#include <godmode.engine/logic/EntityTree.h>
#include <godmode.engine/logic/Lightning.h>
#include <godmode.engine/logic/LogicEntity.h>
#include <godmode.engine/logic/LogicEntity2d.h>
#include <godmode.engine/logic/LogicEntity3d.h>
#include <godmode.engine/logic/LogicEntityType.h>
#include <godmode.engine/logic/Picker.h>
#include <godmode.engine/logic/Refreshable.h>
#include <godmode.engine/logic/Refreshables.h>
#include <godmode.engine/logic/Releaseable.h>
#include <godmode.engine/logic/Scene.h>
#include <godmode.engine/logic/SceneAttachable.h>
#include <godmode.engine/logic/SceneManager.h>
#include <godmode.engine/logic/SceneStateChangeType.h>
#include <godmode.engine/logic/ViewFrustum.h>
#include <godmode.engine/logic/_2d/Camera2d.h>
#include <godmode.engine/logic/_2d/Quadtree.h>
#include <godmode.engine/logic/_2d/Scene2d.h>
#include <godmode.engine/logic/_3d/Camera3d.h>
#include <godmode.engine/logic/_3d/Light.h>
#include <godmode.engine/logic/_3d/Octree.h>
#include <godmode.engine/logic/_3d/Scene3d.h>
#include <godmode.engine/math/float2.h>
#include <godmode.engine/math/float3.h>
#include <godmode.engine/math/float4.h>
#include <godmode.engine/math/float4x4.h>
#include <godmode.engine/math/Math.h>
#include <godmode.engine/math/Plane.h>
#include <godmode.engine/math/Quaternion.h>
#include <godmode.engine/network/NetworkClient.h>
#include <godmode.engine/network/NetworkHost.h>
#include <godmode.engine/network/NetworkPlayer.h>
#include <godmode.engine/physics/CollisionGroup.h>
#include <godmode.engine/physics/ForceField.h>
#include <godmode.engine/physics/NxCharacterController.h>
#include <godmode.engine/physics/NxContactReport.h>
#include <godmode.engine/physics/NxCooking.h>
#include <godmode.engine/physics/NxForceField.h>
#include <godmode.engine/physics/NxHitReportController.h>
#include <godmode.engine/physics/NxMathWrapper.h>
#include <godmode.engine/physics/NxMemoryReadBuffer.h>
#include <godmode.engine/physics/NxMemoryWriteBuffer.h>
#include <godmode.engine/physics/NxPhysicsApi.h>
#include <godmode.engine/physics/NxPhysicsEntity3d.h>
#include <godmode.engine/physics/NxPhysicsScene.h>
#include <godmode.engine/physics/NxPhysicsScene3d.h>
#include <godmode.engine/physics/PhysicsApi.h>
#include <godmode.engine/physics/PhysicsController.h>
#include <godmode.engine/physics/PhysicsEntity3d.h>
#include <godmode.engine/physics/PhysicsEntityType.h>
#include <godmode.engine/physics/PhysicsScene.h>
#include <godmode.engine/sound/AudioInput.h>
#include <godmode.engine/sound/AudioStream.h>
#include <godmode.engine/sound/AudioType.h>
#include <godmode.engine/sound/Channel.h>
#include <godmode.engine/sound/Mixer.h>
#include <godmode.engine/sound/Sampler.h>
#include <godmode.engine/sound/Sound.h>
#include <godmode.engine/sound/SoundApi.h>
#include <godmode.engine/sound/SoundDevice.h>
#include <godmode.engine/sound/SoundFactory.h>
#include <godmode.engine/system/FpsMeter.h>
#include <godmode.engine/system/SystemApi.h>
#include <godmode.engine/system/SystemScreen.h>
#include <godmode.engine/system/SystemWindow.h>
#include <godmode.engine/ui/Application.h>
#include <godmode.engine/ui/AppManager.h>
#include <godmode.engine/ui/apps/ContentApp.h>
#include <godmode.engine/ui/apps/EditorSettingsApp.h>
#include <godmode.engine/ui/apps/EffectJsonSchemaApp.h>
#include <godmode.engine/ui/apps/EffectsApp.h>
#include <godmode.engine/ui/apps/Entity3dApp.h>
#include <godmode.engine/ui/apps/RendererTexturesApp.h>
#include <godmode.engine/ui/apps/SceneManagerApp.h>
#include <godmode.engine/ui/Clipboard.h>
#include <godmode.engine/ui/Component.h>
#include <godmode.engine/ui/components/Button.h>
#include <godmode.engine/ui/components/CheckBox.h>
#include <godmode.engine/ui/components/ComboBox.h>
#include <godmode.engine/ui/components/Container.h>
#include <godmode.engine/ui/components/ContextMenu.h>
#include <godmode.engine/ui/components/GroupBox.h>
#include <godmode.engine/ui/components/ImageBox.h>
#include <godmode.engine/ui/components/Label.h>
#include <godmode.engine/ui/components/ListBox.h>
#include <godmode.engine/ui/components/MenuBar.h>
#include <godmode.engine/ui/components/NumberBox.h>
#include <godmode.engine/ui/components/ScrollBar.h>
#include <godmode.engine/ui/components/Terminal.h>
#include <godmode.engine/ui/components/TerminalCommandEvent.h>
#include <godmode.engine/ui/components/TerminalCommandEventListener.h>
#include <godmode.engine/ui/components/TextBox.h>
#include <godmode.engine/ui/components/TextHistoryItem.h>
#include <godmode.engine/ui/components/TreeBox.h>
#include <godmode.engine/ui/components/TreeBoxItem.h>
#include <godmode.engine/ui/Cursor.h>
#include <godmode.engine/ui/dialogs/OpenDialog.h>
#include <godmode.engine/ui/dialogs/SaveDialog.h>
#include <godmode.engine/ui/GUI.h>
#include <godmode.engine/ui/JsonSchemaApp.h>
#include <godmode.engine/ui/LayoutSection.h>
#include <godmode.engine/ui/Theme.h>
#include <godmode.engine/ui/Window.h>
#include <godmode.engine/utils/CameraController.h>
#include <godmode.engine/utils/EffectsController.h>
#include <godmode.engine/utils/gameplay/Bullet.h>
#include <godmode.engine/utils/gameplay/Character.h>
#include <godmode.engine/utils/gameplay/CharactersAI.h>
#include <godmode.engine/utils/gameplay/Enemy.h>
#include <godmode.engine/utils/gameplay/HUD.h>
#include <godmode.engine/utils/gameplay/NPC.h>
#include <godmode.engine/utils/gameplay/Player.h>
#include <godmode.engine/utils/gameplay/Weapon.h>
#include <godmode.engine/utils/gameplay/Weapons.h>